### ISSUE TITLE
Errors on Arduino Due but not other Arduino.  Canbus.cpp:16:20: fatal error: avr/io.h: No such file or directory

### ISSUE THREAD

**Issue by dookie454** [sparkfun/CAN-Bus_Shield#24]
Help!!   I have two Sparkfun CanBus shields and both work great on Uno, nano, etc.   But when I try to compile on a Due, I get this error: 

Canbus.cpp:16:20: fatal error: avr/io.h: No such file or directory

I've tried to narrow down what is causing the problem, but I cant.  All of the example code works for the Due,  plus a newer FASTLed library also works on Due after it was updated to work with Due, since it showed the same errors originally.    I dont know what changes were made though.  

Thanks!

**Comment by bboyho** [comment]
Hi,

I'm sorry for the delay in reply. The issue in the compile error for the Arduino Due is subtle.

    Canbus.cpp:16:20: fatal error: avr/io.h: No such file or directory

The part about the avr indicates that the library was written specifically for AVR microcontrollers. The Arduino Due uses a different architecture (specifically the SAMD). As a result, the library is not compatible unless you port the code for the SAMD architecture. This would probably require a preprocessor define, mapping pins, and ensuring any registers that may have been used for the library are compatible with the Arduino Due's SAMD.

I recommend simply sticking to the Arduino Uno and Nano that use an AVR microcontroller rather than using an ARM microcontroller.
